{% set name = "cadquery-direct-mesh-plugin" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cadquery_direct_mesh_plugin-{{ version }}.tar.gz
  sha256: d7d27c565f40da31f58010149603038a2a013d28c9153f60025ffbc5dd457575

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - cadquery

test:
  imports:
    - cadquery_direct_mesh_plugin
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/jmwright/cadquery-direct-mesh-plugin
  summary: CadQuery plugin to go directly from a CadQuery assembly to a mesh without relying on external dependencies.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jmwright
